'use client';

import { Download, CheckSquare, Wand2, FlaskConical, Play } from 'lucide-react';

interface AnalysisProps {
    analysis: {
        explanation: string;
        suggestions: string[];
        model: string;
    } | null;
    isAnalyzing: boolean;
    selectedModel: string;
    setSelectedModel: (model: string) => void;
    analysisScope: 'file' | 'project';
    setAnalysisScope: (scope: 'file' | 'project') => void;
    onAnalyze: () => void;
    onSmartFix?: () => void;
    onGenTests?: () => void;
}

const Analysis = ({ 
    analysis, isAnalyzing, selectedModel, setSelectedModel, 
    analysisScope, setAnalysisScope, onAnalyze, onSmartFix, onGenTests
}: AnalysisProps) => {
    const handleDownload = () => {
        if (!analysis) return;
        const content = `CODE ANALYSIS REPORT\n` +
            `====================\n\n` +
            `ARCHITECTURAL LOGIC:\n${analysis.explanation}\n\n` +
            `ACTIONABLE INSIGHTS:\n` +
            analysis.suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n') +
            `\n\nGenerated by CodeShield Intelligence (${analysis.model})`;
        
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `analysis-report-${new Date().getTime()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="h-full p-5 flex flex-col space-y-4 @container animate-in fade-in duration-500 overflow-hidden">
            <h2 className="text-[12px] font-black text-textSecondary uppercase tracking-[0.2em] mb-2 shrink-0">Intelligence</h2>
            
            {/* CONFIG HEADER */}
            <div className="bg-white/5 rounded-xl p-4 @lg:p-5 border border-white/5 shadow-lg shrink-0">
                <div className="flex justify-between items-start mb-6">
                    <div>
                        <div className="flex items-center space-x-2 text-highlight mb-1">
                            <CheckSquare size={20} />
                            <h2 className="text-sm font-bold uppercase tracking-[0.2em]">Intelligence</h2>
                        </div>
                        <p className="text-[10px] text-textSecondary font-medium">Project-Wide Contextual Review</p>
                    </div>
                    {analysis && (
                        <button
                            onClick={handleDownload}
                            title="Download Report"
                            className="p-2 text-textSecondary hover:text-highlight transition-all"
                        >
                            <Download size={16} />
                        </button>
                    )}
                </div>

                {/* Scope & Engine Selections */}
                <div className="space-y-4">
                    <div className="flex flex-col space-y-2">
                        <label className="text-[10px] font-bold text-textSecondary uppercase tracking-widest opacity-60">Analysis Scope</label>
                        <div className="grid grid-cols-2 gap-1 bg-base/40 p-1 rounded-lg border border-borderLine/50">
                            <button 
                                onClick={() => setAnalysisScope('file')}
                                className={`py-1.5 text-[10px] font-bold rounded-md transition-all ${analysisScope === 'file' ? 'bg-highlight text-black shadow-md' : 'text-textSecondary hover:text-white hover:bg-white/5'}`}
                            >
                                Single File
                            </button>
                            <button 
                                onClick={() => setAnalysisScope('project')}
                                className={`py-1.5 text-[10px] font-bold rounded-md transition-all ${analysisScope === 'project' ? 'bg-highlight text-black shadow-md' : 'text-textSecondary hover:text-white hover:bg-white/5'}`}
                            >
                                Whole project
                            </button>
                        </div>
                    </div>

                    <div className="flex flex-col space-y-2">
                        <label className="text-[10px] font-bold text-textSecondary uppercase tracking-widest opacity-60">Execute Engine</label>
                        <select
                            value={selectedModel}
                            onChange={(e) => setSelectedModel(e.target.value)}
                            className="w-full bg-base/60 text-textPrimary text-xs rounded-lg p-2.5 outline-none border border-borderLine focus:border-highlight/50 transition-all cursor-pointer font-vscode-ui"
                        >
                            <option value="gemini-3.1-pro-preview">Gemini 3.1 Pro</option>
                            <option value="mistral-codestral2">Mistral Codestral 2</option>
                        </select>
                    </div>

                    {/* AI ASSISTANT ACTIONS */}
                    <div className="pt-2 flex space-x-2">
                        <button 
                            onClick={onSmartFix}
                            disabled={isAnalyzing || !analysis}
                            className="flex-1 flex items-center justify-center space-x-2 bg-[#ffde59]/10 hover:bg-[#ffde59]/20 text-highlight py-2 rounded-lg text-[10px] font-bold uppercase tracking-widest transition-all border border-highlight/20 disabled:opacity-30"
                            title="Automatically Fix Suggestions"
                        >
                            <Wand2 size={12} />
                            <span>Smart Fix</span>
                        </button>
                        <button 
                            onClick={onGenTests}
                            disabled={isAnalyzing || !analysis}
                            className="flex-1 flex items-center justify-center space-x-2 bg-white/5 hover:bg-white/10 text-white py-2 rounded-lg text-[10px] font-bold uppercase tracking-widest transition-all border border-white/10 disabled:opacity-30"
                            title="Generate Unit Tests"
                        >
                            <FlaskConical size={12} />
                            <span>Gen Tests</span>
                        </button>
                    </div>
                </div>
            </div>

            {/* RESULTS AREA */}
            <div className="bg-cardPanel rounded-lg flex-1 flex flex-col border border-borderLine min-h-0 overflow-hidden shadow-inner font-vscode-ui">
                <div className="p-4 border-b border-borderLine flex justify-between items-center bg-base/30">
                    <h3 className="text-[10px] font-bold text-textSecondary uppercase tracking-widest flex items-center">
                        <CheckSquare size={12} className="mr-2" />
                        Analysis Results
                    </h3>
                    {analysis && !isAnalyzing && (
                        <span className="text-[9px] font-bold text-highlight uppercase font-vscode-mono">{analysis.model}</span>
                    )}
                </div>
                
                <div className="flex-1 bg-base/50 p-5 overflow-y-auto custom-scrollbar">
                    {isAnalyzing ? (
                        <div className="flex flex-col items-center justify-center h-full space-y-4 py-10 text-center">
                            <div className="relative">
                                <div className="w-12 h-12 border-2 border-highlight/10 border-t-highlight rounded-full animate-spin" />
                                <CheckSquare className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-highlight animate-pulse" size={20} />
                            </div>
                            <p className="text-highlight text-[10px] uppercase font-bold tracking-widest animate-pulse">Scanning {analysisScope}... Please Wait.</p>
                        </div>
                    ) : analysis && analysis.suggestions ? (
                        <div className="space-y-6 animate-in fade-in duration-700">
                            <div>
                                <h4 className="text-[11px] font-black text-highlight uppercase tracking-[0.1em] mb-3 flex items-center">
                                    <div className="w-1 h-3 bg-highlight mr-2 rounded-full" />
                                    Architectural Logic
                                </h4>
                                <p className="text-[12px] text-textSecondary leading-[1.8] font-medium tracking-tight bg-white/5 p-3 rounded-lg border border-white/5 italic">
                                    {analysis.explanation}
                                </p>
                            </div>
                            <div>
                                <h4 className="text-[11px] font-black text-highlight uppercase tracking-[0.1em] mb-4 flex items-center">
                                    <div className="w-1 h-3 bg-highlight mr-2 rounded-full" />
                                    Actionable Insights
                                </h4>
                                <ul className="space-y-3">
                                    {analysis.suggestions.map((suggestion, index) => (
                                        <li key={index} className="text-[11px] text-textPrimary/90 flex items-start space-x-3 group bg-white/[0.02] p-2.5 rounded-md hover:bg-white/5 transition-colors border border-transparent hover:border-white/10">
                                            <span className="text-highlight mt-0.5 shrink-0 group-hover:scale-125 transition-transform">•</span>
                                            <span className="leading-relaxed">{suggestion}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-full text-center space-y-4 opacity-30 grayscale pointer-events-none p-6">
                            <CheckSquare size={48} className="text-textSecondary" />
                            <p className="text-textSecondary italic text-[11px] max-w-[220px] leading-relaxed">Select analysis scope and execute the intelligence engine to begin.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default Analysis;
